PORT: "11111"
DEBUG: true
HIDEBANNER: false
DATABASE:
    ENGINE: "postgres"
    USER: "devx"
    PASSWORD: "admin"
    DBNAME: "govdev"
    PORT: "5432"
    HOST: "localhost"
    SSLMODE: "disable"
CACHE:
    ENGINE: "redis"
    HOST: "localhost"
    PORT: "6379"
    DBNAME: 0
    PASSWORD: ""
OBJECTSTORE: 
    HOST: "localhost"
    PORT: "9000"
    ACCESSKEYID: "admin"
    SECRETACCESSKEY: "adminsecret"
    USESSL: false
