PORT: "11111"
DEBUG: true
HIDEBANNER: true
DATABASE:
    ENGINE: "postgres"
    USER: "devx"
    PASSWORD: "admin"
    DBNAME: "govdev"
    PORT: "5432"
    HOST: "localhost"
    SSLMODE: "disable"
CACHE:
    ENGINE: "redis"
    HOST: "localhost"
    PORT: "6379"
    DBNAME: 0
    PASSWORD: ""
